language: elm

env:
   - tf_version=0.12.19 tf_init_cli_options="-input=false" tf_validation_cli_options="" tf_plan_cli_options="-lock=false -input=false" tf_apply_cli_options="-auto-approve -input=false"

install:
   - npm install -g elm@0.19.1-3
   - npm install -g elm-test@0.19.1

stages:
   - test
   - deploy

jobs:
   include:
      - name: "Elm Test"
        stage: test
        script:
           - elm-test
           - elm make src/Main.elm --output=js/vega_graph.js --optimize
